when you create a new topic, this is a sample response:

{u'messages':
  [{u'kind': u'topic',
    u'group': u'8628',
    u'name': u'testing',
    u'creator':
    {
      u'username': u'llimllib',
      u'url': u'/users/llimllib/',
      u'id': u'1284',
      u'img': u'https://secure.gravatar.com/avatar/aa7c1350d93036592f58f165318044db/?default=https%3A%2F%2Fconvore.com%2Fmedia%2Fimages%2Feric.png&amp;s=80'
    },
    u'url': u'/python-chatbot-testing/testing/',
    u'_ts': 1302281638.805795,
    u'id': u'18115',
    u'date_latest_message': 1302281638.778835,
    u'user':
    {
      u'username': u'llimllib',
      u'url': u'/users/llimllib/',
      u'id': u'1284',
      u'img': u'https://secure.gravatar.com/avatar/aa7c1350d93036592f58f165318044db/?default=https%3A%2F%2Fconvore.com%2Fmedia%2Fimages%2Feric.png&amp;s=80'
    },
    u'date_created': 1302281638.778824,
    u'_id': u'cc4a47f8-6200-11e0-a4f2-4040006c4e80',
    u'slug': u'testing'
  }]
}

when you send a message, this is a sample respone:
{u'messages':
  [{u'kind': u'message',
    u'group': u'8628',
    u'embeds': [],
    u'_ts': 1302281833.55284,
    u'topic': {
      u'url': u'/python-chatbot-testing/testing/',
      u'id': u'18115',
      u'name': u'testing'
    },
    u'user': {
      u'username': u'llimllib',
      u'url': u'/users/llimllib/',
      u'id': u'1284',
      u'img': u'https://secure.gravatar.com/avatar/aa7c1350d93036592f58f165318044db/?default=https%3A%2F%2Fconvore.com%2Fmedia%2Fimages%2Feric.png&amp;s=80'
    },
    u'stars': [],
    u'date_created': 1302281833.501348,
    u'message': u'+++++++++++++++++++++++++++++++++++++++++++++++++++++++',
    u'_id': u'405e51e8-6201-11e0-a4f2-4040006c4e80',
    u'id': u'592736'
  }]
}

when you star a message:
{u'kind': u'star',
u'_id': u'19615108-6224-11e0-a4f2-4040006c4e80',
u'star':
{
    u'message_url': u'/python/introducing-the-python-chatbot-gee-i-hope-this-works/595970/',
    u'date_created': 1302296800.508293,
    u'kind': u'star',
    u'message':
    {
        u'embeds': [],
        u'user':
            {
                u'username': u'llimllib',
                u'url': u'/users/llimllib/',
                u'id': u'1284',
                u'img': u'https://secure.gravatar.com/avatar/aa7c1350d93036592f58f165318044db/?default=https%3A%2F%2Fconvore.com%2Fmedia%2Fimages%2Feric.png&amp;s=80'
            },
        u'stars':
            [{
                u'date_created': 1302296800.508293,
                u'user':
                {
                    u'username': u'paulsmith',
                    u'url': u'/users/paulsmith/',
                    u'id': u'1060',
                    u'img': u'https://convore2.s3.amazonaws.com/userpics/1060/1299852512.jpg'
                }
            }],
        u'date_created': 1302296761.104996,
        u'message': u'next up: karma ranking by stars',
        u'id': u'595970'
    },
    u'user':
        {
        u'username': u'paulsmith',
        u'url': u'/users/paulsmith/',
        u'id': u'1060',
        u'img': u'https://convore2.s3.amazonaws.com/userpics/1060/1299852512.jpg'
        }
},
u'user':
{
    u'username': u'paulsmith',
    u'url': u'/users/paulsmith/',
    u'id': u'1060',
    u'img': u'https://convore2.s3.amazonaws.com/userpics/1060/1299852512.jpg'
},
u'_ts': 1302296800.52687
}

This traceback was received sometime around 4/17. Not clear why:

Traceback (most recent call last):
  File "chatbot.py", line 125, in <module>
    main()
  File "chatbot.py", line 93, in main
    r = req({'cursor': cursor}) if cursor else req()
  File "chatbot.py", line 87, in req
    return requests.get('https://convore.com/api/live.json', params=params, auth=conv_auth)
  File "/usr/local/Cellar/python/2.7.1/lib/python2.7/site-packages/requests/core.py", line 445, in get
    return request('GET', url, params=params, headers=headers, cookies=cookies, auth=auth)
  File "/usr/local/Cellar/python/2.7.1/lib/python2.7/site-packages/requests/core.py", line 430, in request
    r.send()
  File "/usr/local/Cellar/python/2.7.1/lib/python2.7/site-packages/requests/core.py", line 204, in send
    self._build_response(why)
  File "/usr/local/Cellar/python/2.7.1/lib/python2.7/site-packages/requests/core.py", line 146, in _build_response
    self.response.headers = getattr(resp.info(), 'dict', None)
  File "/usr/local/Cellar/python/2.7.1/lib/python2.7/urllib.py", line 979, in info
    return self.headers
AttributeError: 'HTTPError' object has no attribute 'headers'

